server:
  port: 28000
  servlet:
    context-path: /geoapi/V1/sampleset-platform
  tomcat:
    max-http-post-size: -1

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://192.168.30.6:31189/sampleset_platform?useSSL=false&useUnicode=true&characterEncoding=utf8
    username: iecas
    password: 123456

  http:
    multipart:
      max-file-size:  5MB
      max-request-seize: 100MB
    encoding:
      force: true
      charset: utf-8
      enabled: true
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 0
      max-file-size: 1000MB  #单个文件数据大小
      max-request-size: 1000000MB #总文件大小

  aop:
    proxy-target-class: true


#mybatis plus 设置
mybatis-plus:
  type-aliases-package: cn.iecas.datasets.image.pojo,cn.iecas.datasets.image.pojo.domain
  mapper-locations: classpath:mapper/*.xml
  configuration:
    jdbc-type-for-null: null
  global-config:
    # 关闭 mybatis-plus的 banner
    banner: false
  type-handlers-package: cn.iecas.sampleset.common.typeHandler


value:
  datasource: lizardfs
  dir:
    rootDir: d:\\temp
    publicRootDir: d:\\data\\traindata\public
  api:
    user-info: http://192.168.2.156:31151/v1.0/airstudio/user/info
    image-info: http://192.168.30.6:18082/geoai/v1/image/

breakpoint:
  upload:
    chunkSize:  5 242 880
