server:
  port: 28000
  servlet:
    context-path: /geoapi/V1/datasets
  tomcat:
    max-http-post-size: -1

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/geo?useSSL=false&useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456
  redis:
    host: localhost
    port: 6379
    jedis:
      pool:
        min-idle: 3
        max-idle: 10
        max-active: 30
        max-wait: 10000
    timeout: 5000
  http:
    multipart:
      max-file-size:  5MB
      max-request-seize: 100MB
    encoding:
      force: true
      charset: utf-8
      enabled: true
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 0
      max-file-size: 1000MB  #单个文件数据大小
      max-request-size: 1000000MB #总文件大小

  aop:
    proxy-target-class: true


#mybatis plus 设置
mybatis-plus:
  type-aliases-package: cn.iecas.datasets.image.pojo,cn.iecas.datasets.image.pojo.domain
  mapper-locations: classpath:mapper/*.xml
  configuration:
    jdbc-type-for-null: null
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: false
  global-config:
    # 关闭 mybatis-plus的 banner
    banner: false
  type-handlers-package: cn.iecas.datasets.image.common.typeHandler

datasource:
  file:
    rootPath: sdfsdf

fastdfs:
  server: localhost:8888

value:
  fastdfs:
    server: localhost:8888
  dir:
    monitorDir: /Users/vanishrain/Desktop/upload  #本地上传路径
    downloadDir: /Users/vanishrain/Desktop/upload/download
    decompressRootDir: /Users/vanishrain/Desktop/upload #/data/fastdfs/data/
    decompressImgDir: /Users/vanishrain/Desktop/upload  #解压路径
    #downloadDir: D:\\imagedataset\\tile\\
#  decompressCmd:
#    rar:
#      list: unrar lb
#      decompress: unrar -o+ x
#    zip:
#      list: unzip -l
#      decompress: unzip -q -o
#    tar:
#      list: tar -tf
#      decompress : tar -x  -C
  postfix:
    img:  jpg #tif,tiff
    attach: ovr
    compressedFile: rar,zip,tar

  downloadPath: D:\\imagedataset\\tile\\
  # compressedFileName: tile.rar

breakpoint:
  upload:
    chunkSize:  5 242 880
